#ifndef INDEX_BUFFER_H
#define INDEX_BUFFER_H

#include <GL/glew.h>

/**
* An index buffer holds index data. The indices stored in the tell opengl
* which vertices to use when drawing an object. The vertices have to be
* stored in the vertex buffer and configured using a vertex array.
*/
class IndexBuffer {
private:
	// The ID of the buffer generated by OpenGL.
	GLuint m_rendererID;

	// How many indices stored in the buffer.
	unsigned int m_count;
public:
	// Creates a buffer given a pointer to the data and the total bytes of the
	// data.
	IndexBuffer(const unsigned int *data, unsigned int count);
	// Delete the buffer.
	~IndexBuffer();

	// Binds the current buffer to GL_ARRAY_BUFFER.
	void Bind() const;
	// Unbinds the current buffer.
	void Unbind() const;

	unsigned int getCount() const;
};

#endif