#ifndef VERTEX_BUFFER_H
#define VERTEX_BUFFER_H

#include <GL/glew.h>

/**
* A vertex buffer holds vertex data. The vertices stored in the vertex buffer
* can be configured using a vertex array and can be drawn using glDrawArrays()
*/
class VertexBuffer {
private:
	// The ID of the buffer generated by OpenGL.
	GLuint m_rendererID;
public:
	// Creates a buffer given a pointer to the data and the total bytes of the
	// data.
	VertexBuffer(const void *data, unsigned int size);
	// Delete the buffer.
	~VertexBuffer();

	// Binds the current buffer to GL_ARRAY_BUFFER.
	void Bind() const;
	// Unbinds the current buffer.
	void Unbind() const;

	// Draws the vertex buffer. First specifies the starting index and count
	// specifies the number of verticies to draw.
	void DrawTriangles(int first, int count) const;
};

#endif