#ifndef VERTEX_BUFFER_H
#define VERTEX_BUFFER_H

#include <GL/glew.h>

/**
* A vertex buffer holds raw vertex data about a mesh. A vertex can consist of position
* data, colour data or other data. A vertex Array can be used to configure how to 
* vertex buffer should be interpreted by opengl.
*/
class VertexBuffer {
private:
	// The ID of the buffer generated by OpenGL.
	GLuint m_rendererID;

	// The total size of the data stored by the buffer in bytes.
	unsigned int m_size;
public:
	// Creates a buffer given a pointer to the data and the total bytes of the
	// data.
	VertexBuffer(const void *data, unsigned int size);
	// Delete the buffer.
	~VertexBuffer();

	// Binds the current buffer to GL_ARRAY_BUFFER.
	void Bind() const;
	// Unbinds the current buffer.
	void Unbind() const;

	// Draws the vertex buffer. First specifies the starting index and count
	// specifies the number of verticies to draw.
	void DrawTriangles(int first, int count) const;
};

#endif